logging:
  level:
    ROOT: INFO
eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://${wpsoft.eureka.client.defaultZone:localhost}:${wpsoft.eureka.server.port:8761}/eureka
  instance:
    appname: administrationms
    instance-id: administrationms:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      zone: primary
      profile: ${spring.profiles.active}
      version: ${info.project.version}
      
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.99, 1.0
    tags:
      application: ${spring.application.name}
  health:
    rabbit:
      enabled: false
    
spring:
  application:
    name: administrationms
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://${db.host:localhost}:${db.port:3306}/${db.name:administrationmsv3}?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: ${db.uid:root}
      password: ${db.pwd:nemapassword}
      hikari:
          auto-commit: false
  jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: MYSQL
      show-sql: false
      hibernate:
        ddl-auto: update
      properties:
          hibernate.id.new_generator_mappings: true
          hibernate.connection.provider_disables_autocommit: true
          hibernate.cache.use_second_level_cache: false
          hibernate.cache.use_query_cache: false
          hibernate.generate_statistics: false
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: false
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/master.xml
    
server:
  port: 18081
  error:
    whitelabel:
      enabled: false
  servlet:
    encoding:
      force: true
    session:
      cookie:
        http-only: true
  max-http-header-size: 65535
  
wpsoft:
  jackson-modules:
    constraint-violation-problem: true
    enabled: true
    hibernate5: true
    hppc: true
    problem: true
  async:
    enabled: true
    security-task-executor: true
  scheduling: true
  administration-aware:
    aspect: true
    token-authentication-provider: true
    security-service: true
    token-provider: true
  security:
    token:
      token-filter: true
    web:
      cors:
        enabled: true
      csrf:
        enabled: false
    